### ISSUE TITLE
bot message - merge & finalization

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#100]
-----------merge-without-score-----------

### 🔄 The PR has been merged.
>[!IMPORTANT]
This pull request is a part of the Race of Sloths and has not been scored yet. Scoring will close in 24 hours! 🕰️

----------final_message---------------

### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of X. Check out the updates in [your profile](https://github.com/ftdgoodluck)! 🎊

------------stale_message-------------

### ❌ PR inactive
This PR has been inactive for two weeks. It's now marked as stale. 
>[!TIP]
If you think it's a mistake, you can restart the bot with `include` command to proceed 🔄

**Comment by ftdgoodluck** [comment]
point by @akorchyn - last two messages may be obsolete as we can make the update in 1st message

**Comment by botezatunear** [comment]
✅ PR is finalized!
Your contribution is much appreciated with a final score of X. Check out the updates in [your profile](https://github.com/ftdgoodluck)! 🎊

If weekly streak completed: "Another weekly streak completed, well done! Check you bonus [your profile]! To keep your weekly streak and get another bonus make pull request next week! Looking forward to see you in race-of-sloths"
If monthly streak completed: "Congratulations @ftdgoodluck! Your PR was highly scored and you completed another monthly streak! To keep your monthly streak make another pull request next month and get 8+ score for it"
First +5% for streak achieved: "We are thrilled to announce that you are added to the Hall of Sloths Fame! From now and forever we will add +5% for every your contribution within race-of-sloths"
Another +5% for streak achied: "It looks like even in the Hall of Sloths Fame you are going to be the first! We grant you another +5$ for every contribution for ever!"

**Comment by botezatunear** [comment]
Less text, need visualization (badges)

**Comment by ftdgoodluck** [comment]
@akorchyn new final message:

Your contribution is much appreciated with a final score of X!
You have received X Sloth points for this contribution
---optional---
You have completed a weekly/monthly streak and received an additional bonus of Y Sloth points!

---optional - should be added only one per ~week
We would appreciate your feedback or contribution idea that you can submit [here](https://github.com/NEAR-DevHub/race-of-sloths/issues/new/choose)


Check out the updates in [your profile](https://github.com/ftdgoodluck)! 🎊
