### ISSUE TITLE
bot message - edited first message after finalization

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#101]
-----------PR excluded -----------------

### This PR has been excluded from the [Race of Sloths](https://github.com/race-of-sloths)

---------scoring-in-process-----------

#### Current status: waiting for scoring
| Reviewer | Score |
|--------|--------|
| @ftdgoodluck  | 5 |
| @botezatunear  | N/A | 

-------------scoring-finalized---------

#### Current status: executed
| Reviewer | Score |
|--------|--------|
| @frol  | 5 |
| @botezatunear  | 8 | 

Final score: 6.5🎉🎉🎉
@ftdgoodluck check out your results on the [Race of Sloths Leaderboard!](https://github.com/race-of-sloths)

**Comment by akorchyn** [comment]
The average score is integer, right now. Just fyi

**Comment by akorchyn** [comment]
> @botezatunear	N/A

We won't be able to update this list based on review added/review removed as I don't get notified in rest about these changes. And updating only by command is not reactive enough, so I would keep only the list of scores

**Comment by ftdgoodluck** [comment]
archiving as duplicate, all covered by #92
