### ISSUE TITLE
In-bot dynamic picture

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#125]
Rationale: change the common picture that is shown inside the bot message to make it more dynamic and rewarding:
1. We show the picture with 3 parameters:
> Rating - change the color of the rating based on the number of lifetime % bonuses that the person has achieved (0 = white, 1 = green, 2 = blue, 3 = purple, 4 = orange, 5 = red). This block should be titled "Rating"
> Streak. Choose a maximum of (max_weekly, max_monthly). If current streak = chosen max streak, add text or visual element "on fire". This block should be titled "Weekly/Monthly streak record"
> Leaderboard place. Choose a minimum of current (global leaderboard place, monthly leaderboard place). This block should be titled "Xth place monthly/global"
If the user has just joined, instead of the leaderboard place we show "Sloth #XXX" picture

2. The picture should be dynamic, based on the current stats of contributor

**Comment by akorchyn** [comment]
![badge](https://github.com/NEAR-DevHub/race-of-sloths/assets/42449190/2bd6753c-b34d-44a0-9fff-c9f17267456a)

**Comment by akorchyn** [comment]
![Uploading badge (1).svg…]()
