### ISSUE TITLE
Shareable profile picture

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#130]
Create a dynamic profile picture that the contributor can share 
- no need to use it as a part of design
- Replace the GitHub info with RoS logo + only GitHub icon + username
- include basic stats that we show on the profile page: # of contributions, rating, global leaderboard place, max week streak, max month streak
- include Hall of Fame rank icon + rank name
- use global statistics

**Comment by akorchyn** [comment]
I have generated from the figma file the following icons.
We would have one endpoint with query parameter ima 
![badge (2)](https://github.com/NEAR-DevHub/race-of-sloths/assets/42449190/a202c4a4-17db-44a3-88a8-8998faa6f532)

![badge (3)](https://github.com/NEAR-DevHub/race-of-sloths/assets/42449190/e84f2325-960f-4619-923c-46234d9fd57b)

**Comment by race-of-sloth-stage** [comment]
![api.staging.race-of-sloths.com/badge/akorchyn]()

**Comment by race-of-sloths** [comment]
![](badge.staging.race-of-sloths.com)
