### ISSUE TITLE
Adding Build DAO Projects to list of approved projects

### ISSUE THREAD

**Issue by jaswinder6991** [NEAR-DevHub/race-of-sloths#137]
Thanks for your interest in joining the Race of Sloths with your project! Before joining, we want to know more about you:

**How can we address you:**
Build DAO

**Your project's GitHub:**
https://github.com/nearbuilders

Below is a list of repos we are interested in at the moment
- [bos-workspace](https://github.com/nearbuilders/bos-workspace)
- [near-bos-webcomponent](https://github.com/nearbuilders/near-bos-webcomponent)
- [gateway](https://github.com/nearbuilders/gateway)
- [near-api-rs](https://github.com/nearbuilders/near-api-lib-rs)
- [near-social-js](https://github.com/nearbuilders/near-social-js)

**Tell us more about your project and why you want to join the Race:**
We provide support systems for open-source contributors to help each other, learn together, and solve real problems.
To support this, we've build a dev environment with a versatile set of tools for interacting with the blockchain OS, enabling greater composability across front end and back end frameworks.
We want to join the race to gamify contributions to our list of OS projects. 

**Say "yes" if you have read our guidelines and terms of service:**
Yes.

**Comment by jaswinder6991** [comment]
> [near-api-rs](https://github.com/nearbuilders/near-api-rs-lib) link is broken. Other repos are great packages for NEAR developers.

Updated the link. Thanks.

**Comment by frol** [comment]
Let's not include near-api-rs just yet. It still looks like an early prototype, and there is also another experiment currently in progress: https://github.com/akorchyn/near-api

I don't have objections to including other repos listed above. @ftdgoodluck Let's add those to the announcements train.

**Comment by jaswinder6991** [comment]
> Let's not include near-api-rs just yet. It still looks like an early prototype, and there is also another experiment currently in progress: https://github.com/akorchyn/near-api
> 
> I don't have objections to including other repos listed above. @ftdgoodluck Let's add those to the announcements train.

Thanks for the update.

**Comment by ftdgoodluck** [comment]
@jaswinder6991 feel free to reach me out in telegram (same nickname) to coordinate the announcement
