### ISSUE TITLE
Auto-include on score command

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#139]
Current logic:
- anyone can include a particular PR in the race (including maintainer)
- `score` command does not work for PR that was not included

Proposed change:
- automatically include pull request into the Race if the first interaction with the bot was the `score` command from the maintainer

Rationale:
Many developers of the repositories that are already a part of the Race still don't know about the Race. Marketing outreach will take some time, and still, some developers spend most of their time in code rather than on X/Telegram. A common practice would be for the maintainer to advertise the Race, by using a single command it would be easier for them to a) let the contributor know about the race and b) immediately deliver some small bonus with a score.

@akorchyn @frol thoughts?

**Comment by frol** [comment]
@ftdgoodluck I don't want maintainers to subscribe users for something without their will. I would like to suggest we design a referral flow for maintainers to use and easily invite contributors to participate, e.g. with `@race-of-sloths invite` command that will trigger the bot to tell the contributor about the Race

**Comment by akorchyn** [comment]
Currently, the flow works the following way:

* The author uses invite/include -> the author gets included

* The maintainer includes/invites/scores ->
  * If the author is already part of the race - the author gets included and scored
  * if the author is not part of the race - the author receives an invitation message
