### ISSUE TITLE
Attract more projects

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#14]
- Create a list of eligible projets (all dependencies and dev-dependencies of nearcore, near-sdk-*, near-api-*)
- approach these projects and ask to participate in Sloth race
```[tasklist]
### Tasks
- [ ] NEAR Mobile
- [ ] HOT
- [x] MNW
- [x] Nearblocks
```

**Comment by jaswinder6991** [comment]
How can we get our os project listed in the current projects supported? We want to test this out.

**Comment by ftdgoodluck** [comment]
@jaswinder6991 Sure! can you please create an issue with the new project submission here https://github.com/NEAR-DevHub/race-of-sloths/issues/new/choose
and feel free to reach me out via telegram (same nickname as here)
