### ISSUE TITLE
Add organization filter as URL parameter

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#140]
implement filtering by organization in the project list and make the filter an argument for the URL

Rationale: once we make a new org announcement, have a short link on the repo list with the featured repos of this org

Next step: we need this as a quick hack right now, there will be another task to implement full filtering on the website later

**Comment by akorchyn** [comment]
It is now implemented: 
race-of-sloths.com/projects?org=near
