### ISSUE TITLE
[NPS]

### ISSUE THREAD

**Issue by almal** [NEAR-DevHub/race-of-sloths#147]
Thanks for your interest in joining the Race of Sloths with your project! Before joining, we want to know more about you:

How can we address you: Learn NEAR Club
Your project's GitHub: https://github.com/Learn-NEAR-Club/ncaptcha-contact7-addon
Tell us more about your project and why you want to join the Race:
nCaptcha Contact Form 7 addon is advanced captcha system prevents spam and bots from infiltrating your site, by integration with near web3 smart contract with nCaptcha service, integrated to you Contact Form 7 plugin.
nCaptcha Contact Form 7 addon is a part of WordPress integration with web3 near blockchain protocol. This plugin provides a specific captcha for the contact form 7 forms and approving submissions after a small tip transaction to https://explorer.mainnet.near.org/accounts/v1.ncaptcha.near smart contract. As a site owner, you can earn money with our plugin! Our unique payment system allows you to receive a portion of the payment for each captcha solved by your users. So not only will you be protecting your site, but you'll also be generating extra revenue at the same time. Revenue is configurable on your side. So all that you need is get original Contact Form 7 form and our nCaptcha addon plugin, register near wallet and install it to your site for spam protection, money earning and joining web3!
Say "yes" if you have read our guidelines and terms of service: yes

**Comment by ftdgoodluck** [comment]
Hello @almal !
TBH, I don't see any pull requests in the repo - can you please clarify your request a bit?

**Comment by ftdgoodluck** [comment]
closing this for now until further communication
