### ISSUE TITLE
[NPS] Potlock Projects

### ISSUE THREAD

**Issue by codingshot** [NEAR-DevHub/race-of-sloths#148]
Thanks for your interest in joining the Race of Sloths with your project! Before joining, we want to know more about you:

How can we address you:
Your project's GitHub: https://github.com/potlock
Tell us more about your project and why you want to join the Race: want to famify contributions
Say "yes" if you have read our guidelines and terms of service:
yes
----
Particular projects repos
https://github.com/PotLock/core
https://github.com/PotLock/potlock-nextjs-app

**Comment by frol** [comment]
@codingshot Those repos have not received any activity from the maintainers in the past month or more, so there is no reason to add them to the race.
