### ISSUE TITLE
[UFB] false negative for bos-workspace 

### ISSUE THREAD

**Issue by elliotBraem** [NEAR-DevHub/race-of-sloths#149]
[bos-workspace](https://github.com/NEARBuilders/bos-workspac) is listed as a project

<img width="1096" alt="Screenshot 2024-07-16 at 4 03 52 PM" src="https://github.com/user-attachments/assets/749805a7-dd42-4e19-b239-a989585c4776">

but getting comment saying it's not:

https://github.com/NEARBuilders/bos-workspace/pull/128#issuecomment-2231731544

**Comment by akorchyn** [comment]
It's resolved now :)
