### ISSUE TITLE
[UFB] Bot should allow to include recently merged PRs

### ISSUE THREAD

**Issue by frol** [NEAR-DevHub/race-of-sloths#152]
![image](https://github.com/user-attachments/assets/9f5d1a8b-30e0-45ce-9a63-19216f57434f)

Let's allow to include a PR within 24h after merge, to avoid such cases

**Comment by akorchyn** [comment]
I have made a small fix for that in the [commit](https://github.com/NEAR-DevHub/race-of-sloths/commit/6c8df72a2e889315a30207359fed25edcbf9f9eb).

Here you can see the results: 
https://github.com/akorchyn/test-bot/pull/54

Well, two messages are annoying, but It requires refactoring a bit to avoid that. Currently, each command writes on its own to the PR) Probably, it would be better if each command populates a list of messages/changes that were done, and then a single write should happen. Though, as a short-term solution, I rollout this :)
