### ISSUE TITLE
[NPS] Adding Ref.Finance Projects to list of approved projects

### ISSUE THREAD

**Issue by marco-sundsk** [NEAR-DevHub/race-of-sloths#155]
Thanks for your interest in joining the Race of Sloths with your project! Before joining, we want to know more about you:

How can we address you:  
Ref.Finance  

Your project's GitHub:  
https://github.com/ref-finance  

Below is a list of repos we are interested in at the moment
- [ref-exchange](https://github.com/ref-finance/ref-contracts)
- [ref-sdk](https://github.com/ref-finance/ref-sdk)
- [boost-farm](https://github.com/ref-finance/boost-farm)

Tell us more about your project and why you want to join the Race:  
Ref is a defi platform on NEAR and aims to provide users with one-stop-shop defi experience.   
We want to join the race to trigger more dev build on top of NEAR since ref is the oldest defi protocol in NEAR.  

Say "yes" if you have read our guidelines and terms of service:
Yes.

**Comment by akorchyn** [comment]
Added
