### ISSUE TITLE
[NPS] Adding Burrow.Finance Projects to list of approved projects

### ISSUE THREAD

**Issue by marco-sundsk** [NEAR-DevHub/race-of-sloths#156]
Thanks for your interest in joining the Race of Sloths with your project! Before joining, we want to know more about you:

How can we address you:
Burrow.Finance

Your project's GitHub:  
https://github.com/burrowHQ
Below is a list of repos we are interested in at the moment
- [burrowland](https://github.com/burrowHQ/burrowland)
- [liquidation-bot](https://github.com/burrowHQ/burrowland-liquidation-bot)
- [burrow-cash](https://github.com/burrowHQ/burrow-cash)
- [landing-page](https://github.com/burrowHQ/burrow-landing)
- [burrow-api](https://github.com/burrowHQ/burrow-api)
- [burrow-sdk-python](https://github.com/burrowHQ/burrow-sdk-python)

Tell us more about your project and why you want to join the Race:  
Burrow is a lending protocol, providing loans of stable coins, main stream tokens, even lp tokens. 
We want to join the race to trigger more dev build on top of NEAR sinceit is the oldest lending protocol in NEAR.  

Say "yes" if you have read our guidelines and terms of service:
Yes.

**Comment by akorchyn** [comment]
Thanks for reaching out. We have added them :)
