### ISSUE TITLE
[NPS] Add dev.near.org to the race of sloths

### ISSUE THREAD

**Issue by charleslavon** [NEAR-DevHub/race-of-sloths#157]
Thanks for your interest in joining the Race of Sloths with your project! Before joining, we want to know more about you:

How can we address you: 
Your project's GitHub: https://github.com/near/near-discovery and https://github.com/near/near-discovery-components/
Tell us more about your project and why you want to join the Race: dev.near.org is the home base for builders on near with contributors from Pagoda and across the ecosystem.  These two repositories are the primary code repositories of dev.near.org
Say "yes" if you have read our guidelines and terms of service:  Probably, but where can I find these? Adding them into a [readme here](https://github.com/NEAR-DevHub/race-of-sloths) would be helpful

**Comment by ftdgoodluck** [comment]
@charleslavon repositories added, enjoy the Race!
