### ISSUE TITLE
New bot message picture

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#163]
User challenges:
1) “Not completed yet… You can do it!”
2) “Well done! Monthly streak is still missing, just do it!”
3) “Great job! Relax and take your time.. Or…”

Rank = Level of Hall of Fame if relevant + add lifetime bonus

**Comment by ftdgoodluck** [comment]
Current version delivered by @sashapais 
https://www.figma.com/file/Ps6e2qMWEaV0a47waFExf8?node-id=2691%3A6204&type=design&fuid=1376918535879596737#923295036

**Comment by botezatunear** [comment]
4 states for streaks: 

1) “Not completed yet… You can do it!”
2) “Weekly streak completed! Monthly streak is still missing, just do it!”
3) “Monthly streak completed! Weekly streak is still missing, just do it!”
4) “Great job! Relax and take your time.. Or…”
