### ISSUE TITLE
[NPS] Add auction example to RoS

### ISSUE THREAD

**Issue by PiVortex** [NEAR-DevHub/race-of-sloths#171]
Thanks for your interest in joining the Race of Sloths with your project! Before joining, we want to know more about you:

How can we address you: Owen 
Your project's GitHub: https://github.com/near-examples/auctions-tutorial
Tell us more about your project and why you want to join the Race: The new mega tutorial repo is here! Let's allow people to earn sloth points by contributing to this new auctions tutorial repo that is part of near-examples.
Say "yes" if you have read our guidelines and terms of service: yes

**Comment by akorchyn** [comment]
Thanks for reaching out. This repository is now part of the RoS!
