### ISSUE TITLE
RoStober - Create a list of potential repositories

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#172]
List of NEAR dependencies
Rust libs, JS libs

**Comment by ftdgoodluck** [comment]
@akorchyn can you please put somewhere a list of candidates?

**Comment by akorchyn** [comment]
https://api.race-of-sloths.com/leaderboard/potential_repos

**Comment by akorchyn** [comment]
It contains 2500+ repos, but we will reach out only 500 that has some activity and filtered
