### ISSUE TITLE
Score not recorded if accidentally mentioning race-of-sloths-bot instead of race-of-sloths

### ISSUE THREAD

**Issue by petersalomonsen** [NEAR-DevHub/race-of-sloths#189]
Notice on this Pull Request, where @race-of-sloths-bot was mentioned instead  of @race-of-sloths. 

https://github.com/NEAR-DevHub/neardevhub-contract/pull/152#pullrequestreview-2357713311

Here you can see that the score was not recorded. In many cases it is the race-of-sloths-bot that appears as the first suggestion in the autocomplete, which might lead to that many scores are lost.

I would propose that @race-of-sloths-bot also would accept bot messages such as `score` and also record and respond to it, just as when mentioning @race-of-sloths.

**Comment by akorchyn** [comment]
It actually recorded: ![Image](https://github.com/user-attachments/assets/352ec84a-6682-408e-a411-520c8e57a04e)

**Comment by akorchyn** [comment]
The thing is that race-of-sloths-bot is ours bot as well, that we were using while we was blocked by GitHub...
Now, it's read-only but we still are planning to read it's notifications for a while:)

**Comment by akorchyn** [comment]
Unfortunately, when we got unblocked, we restored back to the original user bot, but it created a bit of spam from bots. As `race-of-sloths- can't edit `race-of-sloths-bot` messages

**Comment by petersalomonsen** [comment]
All right. Thanks for the clarifications! Closing this then
