### ISSUE TITLE
Populate leaderboard and profile with additional data

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#192]
[Leaderboard]
- Add an additional column "Monthly streak"
- Rename "Streak" -"Weekly streak"
- Display current and max streak - "5 / 13"
- For the monthly streak use the same fire icon, but colored in blue

[Profle]
- Show streaks in the same way, "5 / 13" ([current] / [max])

**Comment by akorchyn** [comment]
Done
