### ISSUE TITLE
[NPS] Add "near-openai" to Race of Sloths

### ISSUE THREAD

**Issue by petersalomonsen** [NEAR-DevHub/race-of-sloths#197]
Thanks for your interest in joining the Race of Sloths with your project! Before joining, we want to know more about you:

How can we address you: My name is Peter Salomonsen, The project name is near-openai

Your project's GitHub: https://github.com/petersalomonsen/near-openai/

Tell us more about your project and why you want to join the Race:

The project started in march 2023, with the showcases of generating music and creating pixel-art NFTs on BOS ( using OpenAI API behind the scenes ). 

- Music demo: https://youtu.be/bUjliEFBcFo
- Pixel art, and minter demo ( which was featured on Mintbase ): https://www.youtube.com/watch?v=6mlotzy2IrE

To provide a subscription-free alternative to using ChatGPT and also pay-per-request, a proxy service was created, charging a small amount of NEAR for each request.

Combined with the [JSinRust Fungible Token example](https://github.com/petersalomonsen/quickjs-rust-near/blob/master/examples/fungibletoken/README.md), a new proxy service is in the making, supporting longer conversations, and also refund of unspent tokens. By using a custom Fungible Token for this, it is possible to handle refunds smoothly in user initiated transactions.

The new proxy service can be found in the ongoing Pull Request here: https://github.com/petersalomonsen/near-openai/pull/11
It is written in Rust, and packaged as a WASI 0.2 WebAssembly Component (using the brand new WebAssembly Component Model).

This particular showcase is also submitted to the RedactedAI hackaton: https://devpost.com/software/jsinrust-nearopenai

And a video demo can be seen here: https://youtu.be/-R_zok--L_A

Say "yes" if you have read our guidelines and terms of service:
yes

**Comment by akorchyn** [comment]
Awesome. Ambitious project. I have added it :)
