### ISSUE TITLE
Guide for maintainers

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#6]
Implement a guide for maintainers

- How to add or remove project from Sloth race
- PR evaluation criteria
- General recommendations

depends on #2

**Comment by ftdgoodluck** [comment]
should mention that a maintainer should not intentionally list a certain repo as a Sloth race participant, however they can stop the bot at any time for a certain repo

**Comment by botezatunear** [comment]
https://docs.google.com/document/d/1N7y1Bnks37VFFRbamTiYNqpvkHxQ-uudmkvMun7lNjo/edit

@ftdgoodluck @akorchyn 
Pls check and edit before the call tomorrow.
