### ISSUE TITLE
Guide for contributors

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#7]
Implement a guide for contributors

- Ethical participation codex
- How to evaluate your PRs by yourself
- General recommendations
```[tasklist]
### Tasks
- [ ] https://github.com/NEAR-DevHub/devbot/issues/8
```

depends on #2

**Comment by ftdgoodluck** [comment]
Add the fact that we can ban a certain contributor from Sloth race in case of obvious system abuse (we should somehow describe how it would work though)

**Comment by botezatunear** [comment]
https://docs.google.com/document/d/1N7y1Bnks37VFFRbamTiYNqpvkHxQ-uudmkvMun7lNjo/edit

**Comment by ftdgoodluck** [comment]
May 07th call outcome: finalize according to the discussion, make shorter versions (keeping the long ones as well)
same stands for #6
