### ISSUE TITLE
bot message - include with streak

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#94]
## 🎉 Hey There, Awesome Maintainer! 🎉

**@ftdgoodluck** is here to present you this awesome pull request. He's an open-source rockstar and currently has the following streak of contributions:

- _⚡️⚡️⚡️⚡️⚡️⚡️⚡️⚡️ __ 8 consecutive days with a pull request!
- _💪💪💪____________ 4 consecutive months with a game changer pull request!

<details>
<summary><strong>🙋 Wonder how you can help him? Click here to discover more! 🔍</strong></summary>

**Here's how you can play your part:**
- 🛑 **Reject this PR:** `@race-of-sloths reject` to send this PR back to the drawing board.
- ⭐ **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
- 🔕 **Pause us:** `@race-of-sloths pause` to stop me on your repo.

Want to know all the ins and outs of the Race of Sloths and our scoring system? Check out our [super fun guide](https://github.com/race-of-sloths). 🎮📚

**Why Your Involvement Matters:**
Your feedback not only helps @ftdgoodluck grow but also fuels the collaborative spirit of our community. Together, we make magic happen! ✨

Thanks for being a rockstar! 🌟🙌

![Sloth Image](https://pbs.twimg.com/profile_images/1791732697376641025/Iw7pTeyp_400x400.jpg)
</details>

**Comment by akorchyn** [comment]
To be honest, it doesn't look appealing to me... And how we display 50 weeks with at least one PR.

Well, I would go with text number instead.
