### ISSUE TITLE
bot message - include first timer

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#95]
## 🎉 Dear Maintainer! 🎉

Race of Sloths continues attracting new users to your project, and now it's time to welcome **@ftdgoodluck** with his first pull request! 

<details>
<summary><strong>🙋 Wonder how you can help him? Click here to discover more! 🔍</strong></summary>

Command list to use
| What do you want | Command | Comment |
|--------|--------|--------|
| Reject this PR | @race-of-sloths reject | if you feel this PR should not be a part of the race |
| Assign score|  @race-of-sloths score [1/2/3/5/8/13] | award score based on your assessment |
| Pause | @race-of-sloths pause | stop the race in this repo| 

Want to know all the ins and outs of the Race of Sloths and our scoring system? Check out our [super fun guide](https://github.com/race-of-sloths). 🎮📚

**Why Your Involvement Matters:**
Your feedback not only helps @ftdgoodluck grow but also fuels the collaborative spirit of our community. Together, we make magic happen! ✨

Thanks for being a rockstar! 🌟🙌

![Sloth Image](https://pbs.twimg.com/profile_images/1791732697376641025/Iw7pTeyp_400x400.jpg)
</details>

**Comment by akorchyn** [comment]
Like the table, but I would remove first column, as it's basically double the meaning of the 3rd

**Comment by akorchyn** [comment]
What's the firsttimer? It's per race-of-sloths or per repo? 
From older messages, I thought, it's first-time usage of us by the user

**Comment by ftdgoodluck** [comment]
closing as it's covered in #92
